apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default 
  name: michinori-scheduler 
  labels:
    app: michinori-scheduler 
    component: michinori-scheduler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: michinori-scheduler
subjects:
- kind: ServiceAccount
  name: michinori-scheduler
  namespace: default 
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:kube-scheduler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: michinori-scheduler
  labels:
    app: michinori-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: michinori-scheduler
  template:
    metadata:
      labels:
        app: michinori-scheduler
    spec:
      serviceAccount: michinori-scheduler
      nodeSelector:
        kubernetes.io/hostname: "node1"
      containers:
      - name: michinori-scheduler
        image: docker.io/bonavadeur/michinori-scheduler:latest
        imagePullPolicy: IfNotPresent